### PR TITLE
Tell mobile Safari not to adjust small text

### LINKED ISSUE #155: Code block on mobile inconsistent
image

On the toolbars page. Lower down on the same page:

image

### PR DESCRIPTION
**Pull request by kylesuss**
Closes #155 

Let's wait on https://github.com/storybookjs/storybook/pull/12545 to merge so that the frontpage builds ok.

### CODE REVIEW

**Comment by kylesuss** [comment]
@domyen do you still have the issue with the comments missing from the top of the code snippet here?

https://deploy-preview-174--storybook-frontpage.netlify.app/docs/react/essentials/toolbars-and-globals

I couldn't reproduce that on the iOS simulator 🤔

**Comment by kylesuss** [comment]
@domyen this is ready for review now!

**Comment by domyen** [comment]
The small text is OK on my iPhone. The comments are still missing though.

**Comment by kylesuss** [comment]
> The comments are still missing though

Seems different -- I'll take a look again though. I couldn't replicate that in the simulator so I thought it may have been fixed. I'll snag an iPhone on Friday and sort it out.

**Comment by kylesuss** [comment]
I'm going to merge this to get the 1 fix out.  Haven't yet had a chance to check the comments.

**Pull request merged**
