### PR TITLE
Update hero video for 6.2

### PR DESCRIPTION
**Pull request by domyen**
Replace hero video on the homepage with an updated version that accounts for 6.2 (controls, sidebar, etc)

### CODE REVIEW

**Comment by jonniebigodes** [comment]
Content-wise is good to me, wondering why the deploy preview is breaking!

**Comment by jonniebigodes** [comment]
@winkerVSbecks do you know why the preview is failing? Or is this supposed to happen?

**Comment by winkerVSbecks** [comment]
@jonniebigodes because the component is trying to access window which isn't available during SSR. I'll push a fix

**Comment by winkerVSbecks** [comment]
@domyen added a lazyload wrapper to the video otherwise it fails during SSR.

**Comment by domyen** [comment]
Thanks, I missed that! 🙏

**Comment by winkerVSbecks** [comment]
@domyen preview is up. You might want to double check that the page loads as expected with lazyloading.

**Pull request merged**
