### PR TITLE
feat: add qwik icon

### PR DESCRIPTION
**Pull request by literalpie**
The framework has been added to the docs site, but the icon is missing.

### CODE REVIEW

**Comment by winkerVSbecks** [comment]
@literalpie this is the docs site. I don't see qwik docs yet. Am I missing something?

**Comment by literalpie** [comment]
Are you looking at "next"

**Comment by winkerVSbecks** [comment]
Do you mean https://github.com/storybookjs/storybook?

**Comment by winkerVSbecks** [comment]
This repo generates storybook.js.org/docs. The icons are used in the framework picker. However, we do not have any docs for QWIK yet. 

CleanShot 2023-01-24 at 19 46 52@2x

**Comment by literalpie** [comment]
I'm trying to fix this
image
Maybe I need to target the next branch though

**Review by winkerVSbecks — APPROVED** [review]

**Pull request merged**
