### PR TITLE
Update StorybookSessions.tsx

### PR DESCRIPTION
**Pull request by joevaugh4n**
Added the two upcoming sessions to the sessions list.

@winkerVSbecks: heads up, I tried setting up the frontpage Storybook locally, to test that this worked, but I ran into some build errors when I tried booting it up. Please let me know if there’s anything else I need to be mindful of for future changes!

### CODE REVIEW

**Comment by joevaugh4n** [comment]
also, fwiw, this is the error I received – any ideas?

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../public/page-data/sq/d/662893876.json' in '/Users/joevaughan/sb-fp/src/components/layout'
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/joevaughan/sb-fp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/joevaughan/sb-fp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/joevaughan/sb-fp/node_modules/neo-async/async.js:6883:13
    at Array.<anonymous> (/Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:950:14)
    at arrayEachFunc (/Users/joevaughan/sb-fp/node_modules/neo-async/async.js:2517:19)
    at Object.parallel (/Users/joevaughan/sb-fp/node_modules/neo-async/async.js:6858:9)
    at NormalModuleFactory._resolveResourceErrorHints (/Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:873:12)
    at /Users/joevaughan/sb-fp/node_modules/webpack/lib/NormalModuleFactory.js:834:18
resolve '../../../public/page-data/sq/d/662893876.json' in '/Users/joevaughan/sb-fp/src/components/layout'
  using description file: /Users/joevaughan/sb-fp/package.json (relative path: ./src/components/layout)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/joevaughan/sb-fp/package.json (relative path: ./public/page-data/sq/d/662893876.json)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json.cjs doesn't exist
      as directory
        /Users/joevaughan/sb-fp/public/page-data/sq/d/662893876.json doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
99% done plugins webpack-hot-middlewarewebpack built preview 9ebf480b2f8020af2445 in 416ms
error Command failed with exit code 1.
```

**Comment by winkerVSbecks** [comment]
@joevaugh4n possibly cause you don't have API keys for one of the data sources. We have a `yarn start:docs-only` command that mocks that stuff. Also, there have some linting errors. Could you fix those please: https://app.circleci.com/pipelines/github/storybookjs/frontpage/4242/workflows/d0a62a5c-bda2-44c1-b421-09035a8a617a/jobs/3317

**Comment by joevaugh4n** [comment]
@winkerVSbecks thanks re. the linting error, i think this _should_ be fixed by my new update

**Comment by joevaugh4n** [comment]
the error was literally 2 blank spaces after the comma 🐳 doh!

hopefully fixed now, currently rebuilding

**Review by winkerVSbecks — APPROVED** [review]

**Pull request merged**
