### PR TITLE
Append version tag to matched packages in snippets

### LINKED ISSUE #532: Manipulate installation snippets to append `@next` to necessary packages
Could be a pre-build script that checks snippets for patterns (e.g. yarn add, npm install) then uses an allow list of packages (e.g. [@storybook/addons, @storybook/theming]) to append the @next tag signifier.

Or there may be a better way to explore.

### PR DESCRIPTION
**Pull request by kylegach**
Closes #532 

See tests for behavior details.

I also made a [demo PR](https://github.com/storybookjs/frontpage/pull/574), to provide a [diff of how the snippets will be changed](https://github.com/storybookjs/frontpage/pull/574/commits/df23a3b0f5bf4b22be746db3b2573e4ee6cbf72e) (when docs are preRelease).

### Before

````md
```sh
npx storybook init
```

```sh
npx storybook@next upgrade --prerelease
```

```sh
yarn add -D @storybook/testing-library @storybook/jest @storybook/addon-interactions
```

`npx storybook init`

`@storybook/testing-library`
````

#### When building _latest_ docs

````md
```sh
npx storybook@latest init
```

<!-- Unchanged, because `--prerelease` flag should always be used with `@next` version -->
```sh
npx storybook@next upgrade --prerelease
```

<!-- Unchanged, because `@latest` is unnecessary here -->
```sh
yarn add -D @storybook/testing-library @storybook/jest @storybook/addon-interactions
```

`npx storybook@latest init`

<!-- Unchanged, because it's inline code and `@latest` is unnecessary here -->
`@storybook/testing-library`
````

#### When building _preRelease_ docs

````md
```sh
npx storybook@next init
```

<!-- Unchanged, because `--prerelease` flag should always be used with `@next` version -->
```sh
npx storybook@next upgrade --prerelease
```

```sh
yarn add -D @storybook/testing-library@next @storybook/jest@next @storybook/addon-interactions@next
```

`npx storybook@next init`

<!-- Unchanged, because it's inline code -->
`@storybook/testing-library`
````

### CODE REVIEW

**Review by winkerVSbecks — APPROVED** [review]
Looks good. And thanks for adding tests.

**Review by jonniebigodes — APPROVED** [review]
@kylegach, this looks great, and going to approve it. However, there are a couple of things that we need to account for once this is out:
- Surface the remainder snippets that are embedded directly in the documentation to avoid confusion.
-  We must not forget the snippets that are in the MDX files (e.g., `installation-problems.mdx`)

Also, one thing I remembered when checking this, specifically the recipes. If we could factor them in, it would make @Integrayshaun 's life easier as well. instead of having him manually update some of the snippets when there's a change. WDYT?

**Comment by kylegach** [comment]
@winkerVSbecks @jonniebigodes — I re-requested reviews from each of you because addressing the comment above required a significant reworking of what you previously approved.

I now update all relevant snippets in _all_ docs files, not just those in the snippets directory. Additionally, the following behavior has changed:

- Different behavior for inline vs. block snippets
    - Do not append tags to inline install snippets
- Different behavior for preRelease vs. non-preRelease
    - Do not append tags to install snippets when not preRelease
    
This PR's description has been updated to reflect this, as has the [demo PR to see a diff of resulting changes](https://github.com/storybookjs/frontpage/pull/574/commits/610a2a128b3895ae052be1ef8e439276c9c46e83).

Finally, the recipes are not versioned (i.e. they are always "latest"), so I did not apply this script to those snippets. They all already use `@latest` appropriately.

**Review by winkerVSbecks — APPROVED** [review]
The updated approach sounds good to me

**Review by jonniebigodes — APPROVED** [review]
@kylegach, thanks for the follow-up and for factoring in the feedback so promptly. Appreciate it. All is good on my end.

**Pull request merged**
