### PR TITLE
Restrict search to current version

### PR DESCRIPTION
**Pull request by kylegach**
- Restrict search to current version
    - Same as we do for current framework

### CODE REVIEW

**Comment by kylegach** [comment]
Here's the resultant Netlify deploy preview: https://61f069e47d481100075eef09--storybook-frontpage.netlify.app/docs/react/get-started/introduction

Search is broken, which I think is because https://github.com/algolia/docsearch-configs/pull/5052 must be merged and then the site must be crawled before these changes are usable.

**Comment by kylesuss** [comment]
> Search is broken, which I think is because algolia/docsearch-configs#5052 must be merged and then the site must be crawled before these changes are usable.

Yeah, that sounds right.

**Review by kylesuss — APPROVED** [review]
Seems good based on what we discussed. Let's see what happens when it gets reindexed!

**Review by winkerVSbecks — APPROVED** [review]

**Comment by winkerVSbecks** [comment]
@kylegach should this work on deploy preview? I'm not getting any search results.

**Comment by kylegach** [comment]
> should this work on deploy preview? I'm not getting any search results.

See my previous comment, @winkerVSbecks: https://github.com/storybookjs/frontpage/pull/332#issuecomment-1021639394

**Comment by kylegach** [comment]
Need to split this into two PRs:

1a. (this one) Add the meta tag
1b. (not a PR) Update Algolia config and re-crawl the site
2. Use the now-available version data in the search

**Comment by kylegach** [comment]
Confirmed that the search is _not_ broken in the deploy preview, so I'm merging.

**Pull request merged**
